## Introduction to Scikit Learn (sklearn)

This notebook demonstrates some of the most usefull functions of the beautifull scikit learn library.

What we are going to cover:

0. An end-to-end Scikit-Learn workflow
1. Getting the data ready
2. Choose the right estimator/model/algorithm for your problem.
3. Fit the model and use it to make predictions on our data.
4. Evaluate the model
5. Improve the model
6. Save and load the trained model.
7. Putting it all together.

### 0. An end-to-end scikit learn workflow.

In [3]:
# 1. Getting the data ready
import pandas as pd
import numpy as np
heart_disease = pd.read_csv("CSV_Files/heart-disease.csv")

In [4]:
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [5]:
# Getting the features/Input matrix
x = heart_disease.drop("target", axis=1)

# Label Matrix 
y = heart_disease["target"]

In [6]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier 
clf = RandomForestClassifier()

# We'll keep the default hyper parameters for now
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [7]:
# 3. Fit the model to the training  data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [8]:
clf.fit(x_train, y_train)

RandomForestClassifier()

In [9]:
# Make a prediction
y_preds = clf.predict(x_test)

In [10]:
y_preds

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [11]:
y_test

230    0
92     1
157    1
256    0
236    0
      ..
159    1
30     1
91     1
251    0
173    0
Name: target, Length: 61, dtype: int64

In [12]:
# 4. Evaluate the model on the training data and test data
clf.score(x_train, y_train)

1.0

In [13]:
clf.score(x_test, y_test)

0.8688524590163934

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.81      0.93      0.86        27
           1       0.93      0.82      0.88        34

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.88      0.87      0.87        61

In [15]:
confusion_matrix(y_test, y_preds)

array([[25,  2],
       [ 6, 28]])

In [16]:
accuracy_score(y_test, y_preds)

0.8688524590163934

In [17]:
# 5. Improve the model

##-> try a different amount of n-estimators
np.random.seed(42)
for i in range(10,101,10):
    print(f"Trying model with {i} estimators.....")
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(x_train, y_train)
    print(f"Model accuracy on test set {clf.score(x_test, y_test)*100:.2f}%")
    print("")

Trying model with 10 estimators.....
Model accuracy on test set 86.89%

Trying model with 20 estimators.....
Model accuracy on test set 85.25%

Trying model with 30 estimators.....
Model accuracy on test set 83.61%

Trying model with 40 estimators.....
Model accuracy on test set 81.97%

Trying model with 50 estimators.....
Model accuracy on test set 88.52%

Trying model with 60 estimators.....
Model accuracy on test set 85.25%

Trying model with 70 estimators.....
Model accuracy on test set 85.25%

Trying model with 80 estimators.....
Model accuracy on test set 85.25%

Trying model with 90 estimators.....
Model accuracy on test set 88.52%

Trying model with 100 estimators.....
Model accuracy on test set 85.25%

In [18]:
# 6. Save a model and load it
import pickle

pickle.dump(clf, open("random-forest-heart-first-ml.pkl", "wb"))

In [19]:
## -> load back the pickle file
loaded_model = pickle.load(open("random-forest-heart-first-ml.pkl", "rb"))
loaded_model.score(x_test,y_test)

0.8524590163934426

In [20]:
# Standard ML Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
## Listify our workflow for easier access
what_we_are_covering = [
"0. An end-to-end Scikit-Learn workflow",
"1. Getting the data ready",
"2. Choose the right estimator/model/algorithm for your problem.",
"3. Fit the model and use it to make predictions on our data.",
"4. Evaluate the model",
"5. Improve the model",
"6. Save and load the trained model.",
"7. Putting it all together."]

## 1. Getting our data ready to be used with machine learning

Three main things we have to do:

    1. Splitting data into features and labels ('x' and 'y')
    
    2. Filling (aka Imputing) or disregarding missing values
    
    3. Converting non-numerical values to numerical values (aka feature encoding)

In [22]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [23]:
x = heart_disease.drop("target", axis=1)
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [24]:
y=heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [25]:
## Split the data into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [26]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

### 1.1. Make sure its all numerical

In [27]:
car_sales = pd.read_csv("CSV_Files/car-sales-extended.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [28]:
len(car_sales)

1000

In [29]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [30]:
# Split into x and y without doing the numerical conversion of the non-numeric data types
x = car_sales.drop("Price", axis=1)
x.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [31]:
y = car_sales["Price"]
y.head()

0    15323
1    19943
2    28343
3    13434
4    14043
Name: Price, dtype: int64

In [32]:
# Split into training and test test
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [33]:
# Build Machine learning model
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()

model.fit(x_train, y_train)
model.score(x_test, y_test)

ValueError: could not convert string to float: 'Toyota'

In [ ]:
## As we can see above , the string data types are throwing errors, and we are unable to proceed unless we convert them to int/double

In [34]:
## Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] # but why doors

In [35]:
car_sales["Doors"].value_counts()

Doors
4    856
5     79
3     65
Name: count, dtype: int64

In [36]:
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                   one_hot, 
                                   categorical_features,
                                   )], remainder="passthrough")
transformed_x = transformer.fit_transform(x)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]], shape=(1000, 13))

In [37]:
pd.DataFrame(transformed_x)

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [38]:
## very wierd but imp
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,4,False,True,False,False,False,False,False,False,True
1,5,True,False,False,False,False,True,False,False,False
2,4,False,True,False,False,False,False,False,False,True
3,4,False,False,False,True,False,False,False,False,True
4,3,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,4,False,False,False,True,True,False,False,False,False
996,3,False,False,True,False,False,False,False,False,True
997,4,False,False,True,False,False,True,False,False,False
998,4,False,True,False,False,False,False,False,False,True
999,4,False,False,False,True,False,True,False,False,False

In [39]:
# Let's refit the model
np.random.seed(42)
x_train, x_test, y_train, y_test = train_test_split(transformed_x,y, test_size=0.2)
model.fit(x_train, y_train)

RandomForestRegressor()

In [40]:
model.score(x_test, y_test)

0.3235867221569877

### 1.2. What if there were missing values

* Fill them with some value (aka Imputation)
* Remove the samples with the missing data all together.

In [41]:
# Import the missing data car sales
car_sales_missing = pd.read_csv("CSV_Files/car-sales-extended-missing-data.csv")
car_sales_missing

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [44]:
car_sales_missing.isna().sum() ## Total missing values in each column

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [46]:
# Create x and y

x=car_sales_missing.drop("Price", axis=1)
y=car_sales_missing["Price"]

#### Option1: fill missing data with pandas

In [49]:
car_sales_missing["Doors"].value_counts()

Doors
4.0    811
5.0     75
3.0     64
Name: count, dtype: int64

In [55]:
# Fill the "Make" Column
car_sales_missing["Make"] = car_sales_missing["Make"].fillna("Missing")

# Fill the "Colour" Column
car_sales_missing["Colour"] = car_sales_missing["Colour"].fillna("Missing")

# Fill the "Odometer (KM)" column
car_sales_missing["Odometer (KM)"] = car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean())

# Fill the "Doors" Column
car_sales_missing["Doors"] = car_sales_missing["Doors"].fillna(car_sales_missing["Doors"].mode()[0])

In [56]:
# Check the dataframe again

car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [57]:
# Remove rows with missing Price value
car_sales_missing.dropna(inplace=True)

In [58]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [59]:
len(car_sales_missing)

950

In [60]:
# Re-split our data
x = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [62]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] # but why doors
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                   one_hot, 
                                   categorical_features,
                                   )], remainder="passthrough")
transformed_x = transformer.fit_transform(car_sales_missing)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]], shape=(950, 16))

## Option 2. Fill missing values with Scikit Learn

In [74]:
car_sales_missing = pd.read_csv("CSV_Files/car-sales-extended-missing-data.csv")
car_sales_missing.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [75]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [80]:
## Drop the rows with No labels
car_sales_missing = car_sales_missing.dropna(subset=["Price"])

In [81]:
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [82]:
# Split the data into x and y
x = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

# Split data into train and test
np.random.seed(42)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [83]:
# Check missing values
x.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [87]:
# Fill the missing values with Scikit-Learn

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill the categorical columns with 'missing' and numerical values with mean
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer= SimpleImputer(strategy="constant", fill_value=car_sales_missing["Doors"].mode()[0])
num_imputer = SimpleImputer(strategy='mean')

# Define the columns for each instance to be imputed on
cat_columns = ["Make", "Colour"]
door_feature = ["Doors"]
num_columns = ["Odometer (KM)"]

# Create a ColumnTransformer class to ensure that the imputer is filled on the necessary columns as intended
imputer = ColumnTransformer([
    ("cat_imputer",cat_imputer, cat_columns),
    ("door_imputer", door_imputer, door_feature),
    ("num_imputer", num_imputer, num_columns)
])

# Fill the train and test value seperately

filled_x_train = imputer.fit_transform(x_train)
filled_x_test = imputer.fit_transform(x_test)

# Check filled_x_train
filled_x_train

array([['Honda', 'White', 4.0, 71934.0],
       ['Toyota', 'Red', 4.0, 162665.0],
       ['Honda', 'White', 4.0, 42844.0],
       ...,
       ['Toyota', 'White', 4.0, 196225.0],
       ['Honda', 'Blue', 4.0, 133117.0],
       ['Honda', 'missing', 4.0, 150582.0]], shape=(760, 4), dtype=object)

In [89]:
# Get our transformed Data Arrays back into the dataframe
car_sales_filled_train = pd.DataFrame(filled_x_train,
                                     columns=["Make","Colour","Doors","Odometer (KM)"])

car_sales_filled_test = pd.DataFrame(filled_x_test,
                                    columns=["Make","Colour","Doors","Odometer (KM)"])

In [92]:
# Check to see missing data in training set
car_sales_filled_train.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [93]:
car_sales_filled_train

       Make   Colour Doors Odometer (KM)
0     Honda    White   4.0       71934.0
1    Toyota      Red   4.0      162665.0
2     Honda    White   4.0       42844.0
3     Honda    White   4.0      195829.0
4     Honda     Blue   4.0      219217.0
..      ...      ...   ...           ...
755  Toyota  missing   4.0      218803.0
756     BMW     Blue   5.0      245427.0
757  Toyota    White   4.0      196225.0
758   Honda     Blue   4.0      133117.0
759   Honda  missing   4.0      150582.0

[760 rows x 4 columns]

In [96]:
## Now we will OneHotEncode the categorical columns to convert into numerical columns, by re-using the same code as before
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                 one_hot, 
                                 categorical_features)],
                                 remainder="passthrough")

# Fill train and test values separately
transformed_x_train = transformer.fit_transform(car_sales_filled_train)
transformed_x_test = transformer.transform(car_sales_filled_test)

In [97]:

# Check transformed and filled X_train
transformed_x_train.toarray()

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 7.19340e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.62665e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 4.28440e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.96225e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.33117e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.50582e+05]], shape=(760, 15))

In [105]:
## Now we will build a model to predict our ans
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

## Now fitting and predicting
model.fit(transformed_x_train, y_train)
model.score(transformed_x_test,y_test)

0.25366332156443805

In [109]:
transformed_x_train.shape[0]+transformed_x_test.shape[0], len(car_sales)

(950, 1000)